enum TasksActionType {
    ADD_TASK = 'ADD_TASK',
    DELETE_TASK = 'DELETE_TASK',
    CHANGE_ORDER_TASK = 'CHANGE_ORDER_TASK',
    CHANGE_PROGRESS_TASK = 'CHANGE_PROGRESS_TASK'
}

export default TasksActionType